-- CREATE DATABASE ESH(EXAMPLE-SPRING-HIBERNATE)
CREATE DATABASE ESH;
USE ESH;

CREATE TABLE esh.APP_USER (
   USER_ID INT AUTO_INCREMENT NOT NULL,
   USER_NAME VARCHAR(20),
   ROLE_ID INT,
   SEX VARCHAR(20),
   USER_TYPE VARCHAR(20),
  PRIMARY KEY (USER_ID)
) ENGINE = InnoDB AUTO_INCREMENT = 1 ROW_FORMAT = DEFAULT CHARACTER SET utf8;

CREATE TABLE esh.APP_DICT (
   DICT_NATURE VARCHAR(20),
   DICT_CODE VARCHAR(20),
   DICT_VALUE VARCHAR(20)
) ENGINE = InnoDB AUTO_INCREMENT = 1 ROW_FORMAT = DEFAULT CHARACTER SET utf8;

CREATE TABLE esh.APP_ROLE (
   ROLE_ID INT AUTO_INCREMENT NOT NULL,
   ROLE_NAME VARCHAR(20),
  PRIMARY KEY (ROLE_ID)
) ENGINE = InnoDB AUTO_INCREMENT = 1 ROW_FORMAT = DEFAULT CHARACTER SET utf8;

CREATE TABLE esh.APP_GROUP (
   GROUP_ID INT AUTO_INCREMENT NOT NULL,
   GROUP_NAME VARCHAR(20),
  PRIMARY KEY (GROUP_ID)
) ENGINE = InnoDB AUTO_INCREMENT = 1 ROW_FORMAT = DEFAULT CHARACTER SET utf8;

CREATE TABLE esh.APP_GROUP_USER (
   GROUP_USER_ID INT AUTO_INCREMENT NOT NULL,
   USER_ID INT NOT NULL,
   GROUP_ID INT NOT NULL,
  PRIMARY KEY (GROUP_USER_ID)
) ENGINE = InnoDB AUTO_INCREMENT = 1 ROW_FORMAT = DEFAULT CHARACTER SET utf8;

INSERT INTO esh.APP_GROUP(GROUP_NAME) VALUES('PROJECT A TEAM');
INSERT INTO esh.APP_GROUP(GROUP_NAME) VALUES('PROJECT B TEAM');

INSERT INTO esh.APP_ROLE(ROLE_NAME) VALUES('Manager');
INSERT INTO esh.APP_ROLE(ROLE_NAME) VALUES('Developer');
INSERT INTO esh.APP_ROLE(ROLE_NAME) VALUES('QA');

INSERT INTO esh.APP_DICT(DICT_NATURE, DICT_CODE, DICT_VALUE) VALUES('SEX', 'M', 'Male');
INSERT INTO esh.APP_DICT(DICT_NATURE, DICT_CODE, DICT_VALUE) VALUES('SEX', 'F', 'Female');
INSERT INTO esh.APP_DICT(DICT_NATURE, DICT_CODE, DICT_VALUE) VALUES('USER_TYPE', 'SA', 'System Administrator');
INSERT INTO esh.APP_DICT(DICT_NATURE, DICT_CODE, DICT_VALUE) VALUES('USER_TYPE', 'AU', 'Application user');

INSERT INTO esh.APP_USER(USER_NAME, ROLE_ID, SEX, USER_TYPE) VALUES('Jimmy', 2, 'M', 'SA');
INSERT INTO esh.APP_USER(USER_NAME, ROLE_ID, SEX, USER_TYPE) VALUES('Sarah', 1, 'F', 'AU');
INSERT INTO esh.APP_USER(USER_NAME, ROLE_ID, SEX, USER_TYPE) VALUES('Shawn', 2, 'M', 'AU');
INSERT INTO esh.APP_USER(USER_NAME, ROLE_ID, SEX, USER_TYPE) VALUES('Tony', 2, 'M', 'AU');
INSERT INTO esh.APP_USER(USER_NAME, ROLE_ID, SEX, USER_TYPE) VALUES('Jack', 2, 'M', 'AU');
INSERT INTO esh.APP_USER(USER_NAME, ROLE_ID, SEX, USER_TYPE) VALUES('Ada', 2, 'F', 'AU');

INSERT INTO esh.APP_GROUP_USER(USER_ID, GROUP_ID) VALUES(1, 1);
INSERT INTO esh.APP_GROUP_USER(USER_ID, GROUP_ID) VALUES(1, 2);
INSERT INTO esh.APP_GROUP_USER(USER_ID, GROUP_ID) VALUES(2, 1);
INSERT INTO esh.APP_GROUP_USER(USER_ID, GROUP_ID) VALUES(2, 2);
INSERT INTO esh.APP_GROUP_USER(USER_ID, GROUP_ID) VALUES(3, 1);
INSERT INTO esh.APP_GROUP_USER(USER_ID, GROUP_ID) VALUES(4, 1);
INSERT INTO esh.APP_GROUP_USER(USER_ID, GROUP_ID) VALUES(5, 2);
INSERT INTO esh.APP_GROUP_USER(USER_ID, GROUP_ID) VALUES(6, 2);
